name: Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only the 'dev' branch can be merged into 'main'."
            exit 1
          fi

          echo "Pull Request is allowed."